language: node_js
node_js: '0.10'
before_script:
- 'npm install'
script:
- 'npm run-script spec'
- 'npm run-script node'
# - 'npm run-script integrate' turn of integrate until available DSTU 2 servers
after_success:
- 'git config --global user.email "robot@health-samurai.io"'
- 'git config --global user.name "Travis CI Deployer"'
- 'if [ -n "$TRAVIS_TAG" ]; then ./script/bower-release.sh; fi'
